name: deploiement docusaurus github page 

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: test
          run: date

        - name: checkout
          uses: actions/checkout@v4

        - name: ls
          run: wget https://github.com/rust-lang/mdBook/releases/download/v0.4.36/mdbook-v0.4.36-x86_64-unknown-linux-musl.tar.gz

        - name: test
          run: tar -xzvf mdbook-v0.4.36-x86_64-unknown-linux-musl.tar.gz

        - name: ls
          run: ls -alh

        - name: init
          run: ./mdbook init test1

        - name: ls
          run: ls -alh  

        - name: ls
          run: ls -alh test1

        - name: cp
          run: |
            cd test1
            sudo cp -r * ./..

        - name: ls
          run: ls -alh 

        - name: ls
          run: ls -alh book

        - name: build
          run: |
             sudo ./mdbook build

        - name: ls book
          run: ls -alh book

        - name: ls .
          run: ls -alh 

        - name: cp
          run: cp github-action workflows.md ./book

        - name: artifact upload
          uses: actions/upload-artifact@v4
          with:
            name: site
            path: book/

    deploiement:
        runs-on: ubuntu-latest
        permissions:
            pages: write     
            id-token: write 
        environment:
                name: github-pages
                url: ${{ steps.deployment.outputs.page_url }}
        steps:
        - name: test
          run: date

        - name: artifact download
          uses: actions/download-artifact@v4
          with: 
            name: site

        - name: ls et creer dossier _site
          run: |
              ls -alh
              mkdir _site
              ls
  
        - name: deplacer dans _site en html
          run: |          
              mv $(ls --ignore=_site) _site/
              ls _site

        - name: Fix permissions
          run: |
            chmod -c -R +rX "_site/" | while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
            done
    
        - name: upload-pages-artifac
          uses: actions/upload-pages-artifact@v3 
              
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
            
        needs: build
    


          




