name: Deploiement Zola gitHub Pages 

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Telechargement de Zola
          run: wget https://github.com/getzola/zola/releases/download/v0.17.1/zola-v0.17.1-x86_64-unknown-linux-gnu.tar.gz

        - name: Desarchive de Zola
          run: tar -xzvf zola-v0.17.1-x86_64-unknown-linux-gnu.tar.gz

        - name: Config.toml
          run: |
            echo 'base_url = "http://example.com"' > config.toml
            echo 'compile_sass = true'>> config.toml
            echo 'build_search_index = false'>> config.toml    
            echo 'title = "Mon Site Zola"' >> config.toml
            mkdir content
            mkdir sass
            mkdir static
            mkdir templates
            mkdir themes

        - name: test
          run: cat config.toml

        - name: Git clone adodoks
          run: |
            cd themes
            git clone https://github.com/codeandmedia/zola_easydocs_theme

        - name: Copie de theme
          run: |
            cp themes/zola_easydocs_theme/config.toml config.toml

        - name: Build
          run: ./zola build

        - name: Artifact upload
          uses: actions/upload-artifact@v4
          with:
            name: site
            path: public

    deploiement:
        runs-on: ubuntu-latest
        permissions:
            pages: write     
            id-token: write 
        environment:
                name: github-pages
                url: ${{ steps.deployment.outputs.page_url }}
        steps:
        - name: ls
          run: ls

        - name: Artifact download
          uses: actions/download-artifact@v4
          with: 
            name: site

        - name: ls et creer dossier _site
          run: |
              ls -alh
              mkdir _site
              ls
  
        - name: Deplacer dans _site en html
          run: |          
              mv $(ls --ignore=_site) _site/
              ls _site

        - name: Fix permissions
          run: |
            chmod -c -R +rX "_site/" | while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
            done
    
        - name: Upload pages artifac
          uses: actions/upload-pages-artifact@v3 
              
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
            
        needs: build
    
