name: deploiement docusaurus github page 

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: test
          run: date

        - name: ls
          run: wget https://github.com/getzola/zola/releases/download/v0.17.1/zola-v0.17.1-x86_64-unknown-linux-gnu.tar.gz

        - name: test
          run: tar -xzvf zola-v0.17.1-x86_64-unknown-linux-gnu.tar.gz

        - name: test
          run: |
            echo 'base_url = "http://example.com"' > config.toml
            echo 'title = "Mon Site Zola"' >> config.toml
            mkdir content
            echo 'Bienvenue sur Mon Site Zola' > content/index.md
            ls
            cat config.toml
            cat content/index.md
            pwd

        - name: build
          run: ./zola build