name: deploiement docusaurus github page 

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: test
          run: date

        - uses: taiki-e/install-action@v2
          with:
            tool: zola@0.17.1

        - name: ls
          run: ls -alh /home/runner/.cargo/bin/zola

        - name: build
          run: zola build